#*******************************************************************************
#* makefile.mk
#*------------------------------------------------------------------------------
#* Makefile used to generate the library binary (GNU ARM format).
#* This file was automatically generated by IngeDev. Please, do not edit!
#*******************************************************************************

#-------------------------------------------------------------------------------
# General constants
#-------------------------------------------------------------------------------
EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

#-------------------------------------------------------------------------------
# Project and file names
#-------------------------------------------------------------------------------
# Project name
PROJECT_NAME   := TMSServiceImpl
# Compiler version
COMPILER_VERSION    := GNU ARM 4.7.3 (HWTetra)
# Configuration name
CFG_NAME        := GNU_ARM_DEBUG_TETRA


#-------------------------------------------------------------------------------
# Directories
#-------------------------------------------------------------------------------
# Binaries directory
BIN_DIR         := Bin
# Object directory
OBJ_DIR         := Obj
# Build files directory
BUILD_FILES_DIR := BuildFiles
# Additional libraries object directory
# (set to blank string if no additional libraries)
ADD_LIBS_OBJ_DIR:= _addLibsObj

#-------------------------------------------------------------------------------
# Input files path for the current configuration
#-------------------------------------------------------------------------------
# Build files path
BUILD_FILES_PATH:= $(BUILD_FILES_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Output files path for the current configuration
#-------------------------------------------------------------------------------
# Object files path
OBJ_PATH        := $(OBJ_DIR)/$(CFG_NAME)
# Binary files path
BIN_PATH        := $(BIN_DIR)/$(CFG_NAME)
# Additional libraries object files path
ADD_LIBS_OBJ_PATH:=$(OBJ_PATH)/$(ADD_LIBS_OBJ_DIR)

#-------------------------------------------------------------------------------
# Compiler, assembler, archiver...
#-------------------------------------------------------------------------------
# Gnu Compiler executable
CC              := arm-islero-linux-gnueabi-gcc.exe
# Gnu Assembler executable
AS              := arm-islero-linux-gnueabi-as.exe
# Gnu Archiver executable
AR              := arm-islero-linux-gnueabi-ar.exe
# Strip debug symbol executable
STRIP           := arm-islero-linux-gnueabi-strip.exe  -g

#-------------------------------------------------------------------------------
# Gnu Win32 tools
#-------------------------------------------------------------------------------
# Remove tool
RM              := rm.exe -fr
# Make directory tool
MKDIR           := mkdir.exe -p
# Copy tool
CP              := cp.exe
# Printf tool
PRINTF          := printf

#-------------------------------------------------------------------------------
# Includes path used in compilation process
#-------------------------------------------------------------------------------
INCLUDES_PATH   := \
-IInc \
-IExpInc \
-IExpInc/Generated \
-ID:/Users/abmkhan/ingeweb_workspace/TMSService/ExpInc/Generated \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/include/c++/4.7.3 \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/include/c++/4.7.3/arm-islero-linux-gnueabi \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/include/c++/4.7.3/backward \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/lib/gcc/arm-islero-linux-gnueabi/4.7.3/include \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/lib/gcc/arm-islero-linux-gnueabi/4.7.3/include-fixed \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/include \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/sysroot/usr/include \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/CommonTools \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/Communication \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/GOAL \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/GTL \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/Pinpad \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/SDK \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/SQLite \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/OS \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/cpp \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/cpp/google \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/cpp/ingenico \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/proto \


#-------------------------------------------------------------------------------
# Includes path used in assembler process
#-------------------------------------------------------------------------------
INCLUDES_ASM_PATH   := \
-IInc \
-IExpInc \
-IExpInc/Generated \
-ID:/Users/abmkhan/ingeweb_workspace/TMSService/ExpInc/Generated \

#-------------------------------------------------------------------------------
# Libraries to be included in archive library
#-------------------------------------------------------------------------------
LIBS            := \

#-------------------------------------------------------------------------------
# Archive library result output file
#-------------------------------------------------------------------------------
LIB_FILE        := $(BIN_PATH)/libTMSServiceImpl.a

#-------------------------------------------------------------------------------
# Default compiler, assembler and archiver options
#-------------------------------------------------------------------------------
# Default compiler options
CC_DEF_OPTS     := -g -c -Wall -fPIC -fstack-protector-all
# Default assembler options
AS_DEF_OPTS     := 
# Default archiver options
AR_DEF_OPTS     :=  crs

#Includes opt file
INCLUDE_FILE_OPT:= $(OBJ_PATH)/includesFiles.opt


#-------------------------------------------------------------------------------
# Specific compiler, assembler and archiver options
#-------------------------------------------------------------------------------
# Specific compiler options
CC_SPEC_OPTS    := -mthumb  -D_ING_GNU_ARM_DEBUG_TETRA
CC_SPEC_OPTS    +=  -D__FRAMEWORK_TELIUM_3__=1 -D_PACKAGE_NAME_=Telium3SDK -DSDK_VERSION=111001 -D__TELIUM3__=1
CC_SPEC_OPTS    +=  -D_ING_APPLI_BINARY_NAME='"libTMSServiceImpl"' -D_ING_APPLI_CURRENT_CONFIG_NAME='"GNU_ARM_DEBUG_TETRA"' -D_ING_APPLI_FULL_BINARY_NAME='"libTMSServiceImpl.a"'
# Specific assembler options
AS_SPEC_OPTS    := -mthumb  --defsym _ING_GNU_ARM_DEBUG_TETRA=1
AS_SPEC_OPTS    +=  $(INCLUDES_ASM_PATH)
# Specific archiver options
AR_SPEC_OPTS    := 

#-------------------------------------------------------------------------------
# Compiler, assembler and archiver options
# default + specific options
#-------------------------------------------------------------------------------
# Compiler options
CC_OPTS         := $(CC_DEF_OPTS) $(CC_SPEC_OPTS)
# Assembler options
AS_OPTS         := $(AS_DEF_OPTS) $(AS_SPEC_OPTS)
# Archiver options (warning: no space between default and specific options)
AR_OPTS         := $(AR_DEF_OPTS)$(AR_SPEC_OPTS)

#-------------------------------------------------------------------------------
# SRC_OBJS is the list of the project object files
#-------------------------------------------------------------------------------
SRC_OBJS        := \
$(OBJ_PATH)/TMSServiceImpl.o \
$(OBJ_PATH)/TMSServiceImplCustom.o \
$(OBJ_PATH)/setParam.o \
$(OBJ_PATH)/getDefaultParam.o \
$(OBJ_PATH)/getParam.o \
$(OBJ_PATH)/download.o \

#-------------------------------------------------------------------------------
# Dependencies
#-------------------------------------------------------------------------------
DEPENDENCIES    := \
$(BUILD_FILES_PATH)/makefile.mk

#-------------------------------------------------------------------------------
# Rule for includes @option file
#-------------------------------------------------------------------------------
$(INCLUDE_FILE_OPT):  $(DEPENDENCIES) | createObjDir
	@echo "Includes file list @option generation: "
	$(PRINTF) "\n \"%s\"" $(INCLUDES_PATH) > $@
	@echo "'Finished building: $@'"
	@echo ""


#===============================================================================
# Rule to make the project
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the library file generation
#-------------------------------------------------------------------------------
$(LIB_FILE): $(SRC_OBJS) $(LIBS)
	@echo "'$@' static library generation in progress..."
	@$(RM) "$@"
	$(AR) $(AR_OPTS) $@ $(SRC_OBJS)
ifneq "$(words $(LIBS))" "0"
	@$(RM) "$(ADD_LIBS_OBJ_PATH)"
	@$(MKDIR) "$(ADD_LIBS_OBJ_PATH)"


	@$(RM) "$(ADD_LIBS_OBJ_PATH)"
endif
ifeq "$(REMOVE_SYMBOLS)" "true"
	@echo "'$@' strip debug symbols in progress..."
	$(STRIP) $@ -o $(dir $@)_$(notdir $@)
endif
	@echo "'$@' static library file generated."

#===============================================================================
# Rule for the compilation process
#===============================================================================
ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/TMSServiceImpl.d
endif
$(OBJ_PATH)/TMSServiceImpl.o: Src/Generated/TMSServiceImpl.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Generated/TMSServiceImpl.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/TMSServiceImpl.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/TMSServiceImplCustom.d
endif
$(OBJ_PATH)/TMSServiceImplCustom.o: Src/TMSServiceImplCustom.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/TMSServiceImplCustom.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/TMSServiceImplCustom.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/setParam.d
endif
$(OBJ_PATH)/setParam.o: Src/TMSService/setParam.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/TMSService/setParam.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/setParam.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/getDefaultParam.d
endif
$(OBJ_PATH)/getDefaultParam.o: Src/TMSService/getDefaultParam.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/TMSService/getDefaultParam.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/getDefaultParam.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/getParam.d
endif
$(OBJ_PATH)/getParam.o: Src/TMSService/getParam.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/TMSService/getParam.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/getParam.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/download.d
endif
$(OBJ_PATH)/download.o: Src/TMSService/download.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/TMSService/download.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/download.o)
	@echo "done!"
endif


#===============================================================================
# Rule for project name and configuration name display
#===============================================================================
.PHONY: displayInfo
displayInfo:
	@echo "                                     *-*-*"
	@echo "--- Project '$(PROJECT_NAME)', Configuration '$(CFG_NAME)', Compiler '$(COMPILER_VERSION)' ---"

#===============================================================================
# Rule for build target progress info display
#===============================================================================
.PHONY: displayBuildInProgress
displayBuildInProgress:
	@echo "Build in progress..."

#===============================================================================
# Rule for output directories creation
#===============================================================================
createObjDir: | $(OBJ_PATH)

$(OBJ_PATH):
	@$(MKDIR) "$(OBJ_PATH)"

createBinDir: | $(BIN_PATH)

$(BIN_PATH):
	@$(MKDIR) "$(BIN_PATH)"


#===============================================================================
# Make build rule
#===============================================================================
.PHONY: build
build: displayInfo displayBuildInProgress createObjDir createBinDir $(LIB_FILE)
	@echo "done!"
