#*******************************************************************************
#* makefile.mk
#*------------------------------------------------------------------------------
#* Makefile used to generate the Application binaries (GNU ARM format).
#* This file was automatically generated by IngeDev. Please, do not edit!
#*******************************************************************************

#-------------------------------------------------------------------------------
# General constants
#-------------------------------------------------------------------------------
EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

#-------------------------------------------------------------------------------
# Project and file names
#-------------------------------------------------------------------------------
# Project name
PROJECT_NAME    := TMSServiceInstance
# Compiler version
COMPILER_VERSION    := GNU ARM 4.7.3 (HWTetra)
#path compiler
PATH_COMPILER       :=D:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/bin
# Configuration name
CFG_NAME        := GNU_ARM_DEBUG_TETRA
# Target file name (without extension)
TRG_FILE_NAME   := TMSServiceI

#------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# Directories
#-------------------------------------------------------------------------------
# Binaries directory
BIN_DIR         := Bin
# Object directory
OBJ_DIR         := Obj
# Build files directory
BUILD_FILES_DIR := BuildFiles

#-------------------------------------------------------------------------------
# Input files path for the current configuration
#-------------------------------------------------------------------------------
# Build files path
BUILD_FILES_PATH:= $(BUILD_FILES_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Output files path for the current configuration
#-------------------------------------------------------------------------------
# Object files path
OBJ_PATH        := $(OBJ_DIR)/$(CFG_NAME)
# Binary files path
BIN_PATH        := $(BIN_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Compiler, linker, assembler, ...
#-------------------------------------------------------------------------------
# Gnu Compiler executable
CC              := arm-islero-linux-gnueabi-gcc.exe
# Gnu Assembler executable
AS              := arm-islero-linux-gnueabi-as.exe
# Gnu Linker executable
LD              := arm-islero-linux-gnueabi-ld.exe
# Gnu binary file transforming executable
OBJ_COPY        := arm-islero-linux-gnueabi-objcopy.exe
# Gnu binary sections size executable
SIZE            := arm-islero-linux-gnueabi-size.exe
# Gnu binary Obj Dump executable
OBJ_DUMP        := arm-islero-linux-gnueabi-objdump.exe
# Gnu binary strip executable
STRIP           := arm-islero-linux-gnueabi-strip.exe


#-------------------------------------------------------------------------------
# Gnu Win32 tools
#-------------------------------------------------------------------------------
# Remove tool
RM              := rm.exe -fr
# Make directory tool
MKDIR           := mkdir.exe -p
# Copy tool
CP              := cp.exe
# Printf tool
PRINTF          := printf

#-------------------------------------------------------------------------------
# Includes path used in compilation process
#-------------------------------------------------------------------------------
INCLUDES_PATH   := \
-IInc \
-ID:/Users/abmkhan/ingeweb_workspace/TMSService/ExpInc \
-ID:/Users/abmkhan/ingeweb_workspace/TMSService/ExpInc/Generated \
-ID:/Users/abmkhan/Ingenico_Workspace/TMSServiceImpl/ExpInc \
-ID:/Users/abmkhan/Ingenico_Workspace/TMSServiceImpl/ExpInc/Generated \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/include/c++/4.7.3 \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/include/c++/4.7.3/arm-islero-linux-gnueabi \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/include/c++/4.7.3/backward \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/lib/gcc/arm-islero-linux-gnueabi/4.7.3/include \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/lib/gcc/arm-islero-linux-gnueabi/4.7.3/include-fixed \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/include \
-isystemD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/sysroot/usr/include \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/CommonTools \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/Communication \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/GOAL \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/GTL \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/Pinpad \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/SDK \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/Platform/SQLite \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/c/OS \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/cpp \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/cpp/google \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/inc/cpp/ingenico \
-IC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/proto \

#-------------------------------------------------------------------------------
# Includes path used in assembler process
#-------------------------------------------------------------------------------
INCLUDES_ASM_PATH   := \
-IInc \
-ID:/Users/abmkhan/ingeweb_workspace/TMSService/ExpInc \
-ID:/Users/abmkhan/ingeweb_workspace/TMSService/ExpInc/Generated \
-ID:/Users/abmkhan/Ingenico_Workspace/TMSServiceImpl/ExpInc \
-ID:/Users/abmkhan/Ingenico_Workspace/TMSServiceImpl/ExpInc/Generated \


#-------------------------------------------------------------------------------
# Libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS            := \
D:/Users/abmkhan/Ingenico_Workspace/TMSServiceImpl/Bin/GNU_ARM_DEBUG_TETRA/libTMSServiceImpl.a \
D:/Users/abmkhan/ingeweb_workspace/TMSService/Bin/GNU_ARM_DEBUG_TETRA/libTMSServi.so \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBGRAPHICLIB.LIB \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBBATTERY.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBBLIGHT.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBBUZZER.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBCAPTURE.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBPPADTEXT.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBGPS.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBDESKTOP.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libethernet.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBEXPLORER.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libgprs.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libspmci.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libwifi.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBGRAPHICS.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBACCELERO.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBHEADER.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBINACTIVI.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/liblinklayer.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libtmscall.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libtmsdownload.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libmodem.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBMONITOR.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBOS.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libpackip.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libprinter.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBPROTOBUF.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBSCRSAVER.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBSERVICE.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libSecurity.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBSETTING.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libsoftmgt.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBSVCDIRPX.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBSVCDIRSK.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libTrEngine.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBVIRT_KB.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LIBOSLAYER.LIB \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libtlvtree.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/SQLITELIB.a \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/LibBridge.T3L \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/libbluetooth.lib \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform/DAL_Lib.a \

#-------------------------------------------------------------------------------
# System libraries path to be included during link operation
#-------------------------------------------------------------------------------
SYSTEM_LIBS_PATH     := \
-LD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/lib/gcc/arm-islero-linux-gnueabi/4.7.3 \
-LD:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/lib \
-LC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform \
-LC:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/OS \




#-------------------------------------------------------------------------------
# RPATH for libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS_RPATH_LINK   := \
-rpath-link=D:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/lib/gcc/arm-islero-linux-gnueabi/4.7.3 \
-rpath-link=D:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/lib \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/OS \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib_for_dbg \
-rpath-link=D:/Users/abmkhan/ingeweb_workspace/TMSService/Bin/GNU_ARM_DEBUG_TETRA \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/Platform \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/lib/OS \


#-------------------------------------------------------------------------------
# Package libraries to be included during link operation
#-------------------------------------------------------------------------------
PACKAGE_LIBS    :=\
-lchip \
-lcless \
-lgtl \
-lled \
-lPpad \
-lswipe \
-ltransac \
-ltelinux \

#-------------------------------------------------------------------------------
# System libraries to be included during link operation
#-------------------------------------------------------------------------------
SYS_LIBS     :=\
-lc \
-lgcc \
-lgcc_s \
-lstdc++ \

#-------------------------------------------------------------------------------
# System libraries to be included during link operation
#-------------------------------------------------------------------------------
SYSTEM_LIBS     :=\
	$(PACKAGE_LIBS)\
	$(SYS_LIBS)


#-------------------------------------------------------------------------------
# Compilation and link input files
#-------------------------------------------------------------------------------
# Mapping file location (used during link process)

#-------------------------------------------------------------------------------
# Result output files
#-------------------------------------------------------------------------------
# Binary file
BINARY_FILE     := $(BIN_PATH)/$(TRG_FILE_NAME).BIN
BINARY_FILE_NO_STRIP     := $(OBJ_PATH)/$(TRG_FILE_NAME).T3A

#-------------------------------------------------------------------------------
# Result Listing files
#-------------------------------------------------------------------------------
# Binary file
LST_FILE     := $(OBJ_PATH)/$(TRG_FILE_NAME).lst

#-------------------------------------------------------------------------------
# Intermediate files
#-------------------------------------------------------------------------------
# Result map file location
INTER_MAP_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).map
# AXF file location
INTER_AXF_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).axf
# SIZE file location
INTER_SIZE_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).siz
#Includes opt file
INCLUDE_FILE_OPT:= $(OBJ_PATH)/includesFiles.opt
#Linker opt file
LD_OPT_FILE:=$(OBJ_PATH)/ldFile.opt

#-------------------------------------------------------------------------------
# Default compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Default compiler options
CC_DEF_OPTS     := -g -c -Wall -fstack-protector-all
# Default assembler options
AS_DEF_OPTS     := 
# Default linker options
LD_DEF_OPTS     := -z noexecstack --as-needed -I/lib/ld-linux.so.3 --exclude-libs ALL -Map=$(INTER_MAP_FILE)
# Default linker options
OD_DEF_OPTS     := --disassemble --source --syms

#-------------------------------------------------------------------------------
# Specific compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Specific compiler options
CC_SPEC_OPTS    := -mthumb  -D_ING_GNU_ARM_DEBUG_TETRA
CC_SPEC_OPTS    +=  -D__FRAMEWORK_TELIUM_3__=1 -D_PACKAGE_NAME_=Telium3SDK -DSDK_VERSION=111001 -D__TELIUM3__=1
CC_SPEC_OPTS    +=  -D_ING_APPLI_BINARY_NAME='"TMSServiceI"' -D_ING_APPLI_FAMILY='"TMSServiceInsta"' -D_ING_APPLI_TYPE=0x201 -D_ING_APPLI_TELIUM_TETRA_FULL_BINARY_NAME='"TMSServiceI.T3A"' -D_ING_APPLI_TELIUM_COMPATIBILITY='"Telium Tetra"' -D_ING_APPLI_SIGN_MODE='"Unsigned"' -D_ING_APPLI_DATA_FILE_TELIUM_TETRA_BINARY_NAME='"DATA0201250.T3P"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_NAME='"2500000513010100_TMSServiceInsta.P3A"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_TYPE='"A"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_RANGE='"00"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_COUNTRY_CODE='"250"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_IDENTIFIER='"513"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_VERSION='"010100"' -D_ING_APPLI_TELIUM_TETRA_COMPONENT_NAME='"TMSServiceI.T3A"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_FAMILY='"TMSServiceInsta"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_ROOTNAME='"2500000513010100_TMSServiceInsta"' -D_ING_APPLI_CURRENT_CONFIG_NAME='"GNU_ARM_DEBUG_TETRA"' -D_ING_APPLI_FULL_BINARY_NAME='"TMSServiceI.T3A"'
# Specific assembler options
AS_SPEC_OPTS    := -mthumb  --defsym _ING_GNU_ARM_DEBUG_TETRA=1
AS_SPEC_OPTS    +=  $(INCLUDES_ASM_PATH)
# Specific linker options
LD_SPEC_OPTS    := 
# Specific strip options
ST_SPEC_OPTS    :=  --remove-section=.comment 

#-------------------------------------------------------------------------------
# Compiler, linker, assembler options
# default + specific options
#-------------------------------------------------------------------------------
# Compiler options
CC_OPTS         := $(CC_DEF_OPTS) $(CC_SPEC_OPTS)
# Assembler options
AS_OPTS         := $(AS_DEF_OPTS) $(AS_SPEC_OPTS)
# Linker options
LD_OPTS         := $(LD_DEF_OPTS) $(LD_SPEC_OPTS)
#ObjDump options
OD_OPTS         := $(OD_DEF_OPTS)
#Strip options
ST_OPTS         := $(ST_SPEC_OPTS)

#-------------------------------------------------------------------------------
# SRC_OBJS is the list of the project object files
#-------------------------------------------------------------------------------
SRC_OBJS        := \
$(OBJ_PATH)/main.o \

#-------------------------------------------------------------------------------
# Dependencies
#-------------------------------------------------------------------------------
DEPENDENCIES    := \
$(BUILD_FILES_PATH)/makefile.mk

#===============================================================================
# Rule to make the project
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the binary files generation
#-------------------------------------------------------------------------------
$(BINARY_FILE): $(INTER_SIZE_FILE) \

	$(OBJ_COPY) -O elf32-littlearm $(INTER_AXF_FILE) $@
	@echo "duplicate bin file :  $@ to $(BINARY_FILE_NO_STRIP)"
	$(CP) $@ $(BINARY_FILE_NO_STRIP)
	@echo "Stripping terminal binary file: "
	$(STRIP) $(ST_OPTS) $@
	@echo "'$@' binary file generated."

#===============================================================================
# Rule for startup files rules generation
#===============================================================================
START_OBJS:= D:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/sysroot/usr/lib/crti.o \
D:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/sysroot/usr/lib/crt1.o \
D:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/lib/gcc/arm-islero-linux-gnueabi/4.7.3/crtbegin.o \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/startfiles/stapp_legacyentrypoint.o \

END_OBJS:= D:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/lib/gcc/arm-islero-linux-gnueabi/4.7.3/crtend.o \
D:/Ingenico/IngeDev_8.6.0.10/toolchains/gnuArm47v7a/arm-islero-linux-gnueabi/sysroot/usr/lib/crtn.o \
C:/Program\ Files/TeliumSDK/SDK11.10.1.01/SDKT3/HW_TETRA/gnu_473/startfiles/stapp_legacyexitpoint.o \


#-------------------------------------------------------------------------------
# Rule for includes @option file
#-------------------------------------------------------------------------------
$(INCLUDE_FILE_OPT):  $(DEPENDENCIES) | createObjDir
	@echo "Includes file list @option generation: "
	@$(PRINTF) "\n \"%s\"" $(INCLUDES_PATH) > $@
	@echo "'Finished building: $@'"
	@echo ""
#===============================================================================
# Rule for linker opt files rules generation
#===============================================================================
$(LD_OPT_FILE):  $(DEPENDENCIES) $(SRC_OBJS)  $(LIBS) \
	$(START_OBJS) $(END_OBJS)

	@echo ""
	@echo "Linker file @option generation"
	@$(PRINTF) "\n \"%s\" " $(START_OBJS) $(SYSTEM_LIBS_PATH) > $@
	@$(PRINTF) "\n \"%s\" " $(LIBS_RPATH_LINK) $(SRC_OBJS) >> $@
	@$(PRINTF) "\n \"%s\" " "--start-group"  $(LIBS) $(SYSTEM_LIBS) "--end-group" $(END_OBJS) >> $@
	@echo "'Finished building: $@'"
	@echo ""

#-------------------------------------------------------------------------------
# Rule for the axf file generation
#-------------------------------------------------------------------------------
$(INTER_AXF_FILE): $(LD_OPT_FILE) \
	$(SRC_OBJS)

	@echo "'$@' link in progress..."
	$(LD) $(LD_OPTS)  -o $@ \
	@$(LD_OPT_FILE)

	@echo "'Finished building: $@'"
	@echo ""

#-------------------------------------------------------------------------------
# Rule for the elf file generation
#-------------------------------------------------------------------------------
$(INTER_SIZE_FILE): $(INTER_AXF_FILE)
	@echo "'Invoking: GNUARM Print Size'"
	$(SIZE) -A $< > $@
	@echo "'Finished building: $@'"
	@echo ""

#===============================================================================
# Rule for the .lst Generation
#===============================================================================
$(LST_FILE): $(INTER_AXF_FILE)
	$(OBJ_DUMP) $(OD_OPTS) $<  > $@
	@echo "'$@' lst file generated."

#===============================================================================
# Rule for the compilation process
#===============================================================================
ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/main.d
endif
$(OBJ_PATH)/main.o: Src/main.cpp $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/main.cpp' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/main.o)
	@echo "done!"
endif


#===============================================================================
# Rule for project name and configuration name display
#===============================================================================
.PHONY: displayInfo
displayInfo:
	@echo "                                     *-*-*"
	@echo "--- Project '$(PROJECT_NAME)', Configuration '$(CFG_NAME)', Compiler '$(COMPILER_VERSION)' ---"

#===============================================================================
# Rule for build target progress info display
#===============================================================================
.PHONY: displayBuildInProgress
displayBuildInProgress:
	@echo "Build in progress..."

#===============================================================================
# Rule for output directories creation
#===============================================================================
createObjDir: | $(OBJ_PATH)

$(OBJ_PATH):
	@$(MKDIR) "$(OBJ_PATH)"

createBinDir: | $(BIN_PATH)

$(BIN_PATH):
	@$(MKDIR) "$(BIN_PATH)"

#===============================================================================
# Make build rule
#===============================================================================
.PHONY: build
build: displayInfo displayBuildInProgress createObjDir createBinDir $(BINARY_FILE)
	@echo "done!"
